In [1]:
import csv
import pandas as pd
import numpy as np
from google.cloud import bigquery
from google.oauth2 import service_account
from google.cloud.bigquery import magics

In [2]:
import os
BIGQUERY_PROJECT = 'cloud-test-ironhacks'
BIGQUERY_KEYPATH = 'cloud-test-ironhacks-052e1ced8b54.json'

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = BIGQUERY_KEYPATH
bigquery_client = bigquery.Client(project=BIGQUERY_PROJECT)

In [3]:
query = """
SELECT * FROM `cloud-test-ironhacks.dwd_data.suppression_remove`
"""

query_job = bigquery_client.query(query)
data = query_job.to_dataframe()
data.head()

,uu_id,timeperiod,week_number,countyfips,tract,tract_name,total_claims,edu_8th_or_less,edu_grades_9_11,edu_hs_grad_equiv,...,gender_female,gender_male,gender_na,race_amerindian,race_asian,race_black,race_noanswer,race_hawaiiannative,race_other,race_white
0,9bee42b55f891413ae7fac2d9d89280a,20210102,1,18003,100,"Census Tract 1, Allen County, Indiana",30.0,0.0,NaN,NaN,...,10.0,20.0,0.0,NaN,0.0,NaN,0.0,0.0,NaN,24.0
1,9bee42b55f891413ae7fac2d9d89280a,20210109,2,18003,100,"Census Tract 1, Allen County, Indiana",51.0,NaN,NaN,25.0,...,22.0,29.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,42.0
2,9bee42b55f891413ae7fac2d9d89280a,20210116,3,18003,100,"Census Tract 1, Allen County, Indiana",39.0,0.0,0.0,NaN,...,16.0,23.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,27.0
3,9bee42b55f891413ae7fac2d9d89280a,20210123,4,18003,100,"Census Tract 1, Allen County, Indiana",36.0,NaN,NaN,16.0,...,13.0,23.0,0.0,NaN,0.0,NaN,NaN,0.0,0.0,28.0
4,9bee42b55f891413ae7fac2d9d89280a,20210130,5,18003,100,"Census Tract 1, Allen County, Indiana",49.0,0.0,NaN,30.0,...,NaN,NaN,0.0,NaN,0.0,NaN,0.0,0.0,NaN,43.0

In [4]:
data = data.fillna(0)
data

,uu_id,timeperiod,week_number,countyfips,tract,tract_name,total_claims,edu_8th_or_less,edu_grades_9_11,edu_hs_grad_equiv,...,gender_female,gender_male,gender_na,race_amerindian,race_asian,race_black,race_noanswer,race_hawaiiannative,race_other,race_white
0,9bee42b55f891413ae7fac2d9d89280a,20210102,1,18003,100,"Census Tract 1, Allen County, Indiana",30.0,0.0,0.0,0.0,...,10.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0
1,9bee42b55f891413ae7fac2d9d89280a,20210109,2,18003,100,"Census Tract 1, Allen County, Indiana",51.0,0.0,0.0,25.0,...,22.0,29.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,42.0
2,9bee42b55f891413ae7fac2d9d89280a,20210116,3,18003,100,"Census Tract 1, Allen County, Indiana",39.0,0.0,0.0,0.0,...,16.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.0
3,9bee42b55f891413ae7fac2d9d89280a,20210123,4,18003,100,"Census Tract 1, Allen County, Indiana",36.0,0.0,0.0,16.0,...,13.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.0
4,9bee42b55f891413ae7fac2d9d89280a,20210130,5,18003,100,"Census Tract 1, Allen County, Indiana",49.0,0.0,0.0,30.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,43.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55877,20f6ad2e745b760f4d67491c4c9f2881,20210807,32,18127,990000,"Census Tract 9900, Porter County, Indiana",0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55878,20f6ad2e745b760f4d67491c4c9f2881,20210814,33,18127,990000,"Census Tract 9900, Porter County, Indiana",0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55879,20f6ad2e745b760f4d67491c4c9f2881,20210821,34,18127,990000,"Census Tract 9900, Porter County, Indiana",0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55880,20f6ad2e745b760f4d67491c4c9f2881,20210828,35,18127,990000,"Census Tract 9900, Porter County, Indiana",0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55881,20f6ad2e745b760f4d67491c4c9f2881,20210904,36,18127,990000,"Census Tract 9900, Porter County, Indiana",0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
poi_names = np.unique(data['uu_id'].to_numpy())
raw_rows = data['uu_id'].to_numpy()
poi_id = []
for r in raw_rows:    
    poi_id.append(np.where(poi_names==r)[0][0])

In [6]:
raw_counts=data[['total_claims']].to_numpy()
week_number=data[['week_number']].to_numpy()

week_start = 11
number_poi = len(poi_names)
number_weeks = 44-week_start
visit_mat = np.zeros((number_poi,number_weeks))
for i in np.arange(len(raw_rows)):
    visit_mat[poi_id[i],week_number[i]-week_start]=raw_counts[i]

In [11]:
# linear regression
window_size = 14
X=np.ones((number_poi*(number_weeks-window_size),window_size+1))
y=np.zeros((number_poi*(number_weeks-window_size),1))
X_pred = np.ones((number_poi,window_size+1))
i = 0
i_poi = 0
for visit_ in visit_mat:
    for j in np.arange(36-week_start-window_size):
        X[i,:-1]=visit_[j:(j+window_size)]
        y[i] = visit_[(j+window_size)]
        i = i + 1
    j = j + 1
    X_pred[i_poi,:-1] = visit_[j:(j+window_size)]
    i_poi = i_poi + 1

In [12]:
visit_[(j+window_size)]

22.0

In [13]:
visit_[j:(j+window_size)]

array([ 0., 20., 33., 24., 16., 20., 34., 14., 19., 25., 16., 10.,  0.,
       24.])

In [14]:
visit_

array([31., 17., 22., 26., 66., 56., 33., 28., 41., 19., 29.,  0., 20.,
       33., 24., 16., 20., 34., 14., 19., 25., 16., 10.,  0., 24., 22.,
       23., 33., 39., 38., 41., 35.,  0.])

In [15]:
X

array([[12., 11., 10., ...,  0.,  0.,  1.],
       [11., 10., 15., ...,  0.,  0.,  1.],
       [10., 15., 21., ...,  0.,  0.,  1.],
       ...,
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.]])

In [16]:
y

array([[ 0.],
       [ 0.],
       [11.],
       ...,
       [ 0.],
       [ 0.],
       [ 0.]])

In [17]:
X_pred

array([[ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0., 40., 47., ..., 21., 29.,  1.],
       [ 0., 24., 27., ..., 14., 11.,  1.],
       ...,
       [ 0., 46., 54., ..., 28., 23.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0., 20., 33., ...,  0., 24.,  1.]])

In [18]:
visit_[j:(j+window_size)]

array([ 0., 20., 33., 24., 16., 20., 34., 14., 19., 25., 16., 10.,  0.,
       24.])

In [19]:
coefs=np.matmul(np.linalg.inv(np.matmul(X.transpose(),X)),np.matmul(X.transpose(),y))
coefs

array([[-0.10462078],
       [ 0.28959346],
       [ 0.15825459],
       [-0.06898746],
       [ 0.01922957],
       [ 0.08577267],
       [ 0.00567305],
       [ 0.1296197 ],
       [-0.14804473],
       [ 0.01373792],
       [ 0.04918467],
       [ 0.0736374 ],
       [ 0.15557987],
       [ 0.27470219],
       [-0.95933275]])

In [20]:
len(poi_names)

1511

In [21]:
y_pred=np.matmul(X_pred,coefs)
len(y_pred)

1511

In [23]:
import pandas as pd 
df=pd.DataFrame(y_pred)
df['uu_id']=poi_names
df=df.rename(columns={0: "total_claims"})

df=df[['uu_id','total_claims']]
df.to_csv('submission_prediction_output.csv',index=False)